# hook configure

apiVersion: v1
kind: ConfigMap
metadata:
  name: hooks-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: hooks-config
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: knitfab
data:
  hooks.yaml: |
{{ tpl (.Files.Get "assets/extensions/hooks.yaml.tpl") . | indent 4 }}
