- name: Create export dir
  file:
    path: "{{ nfs_export_root }}"
    state: directory
    mode: 0777
    owner: nobody

- name: Ensure NFS utilities are installed.
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nfs-kernel-server

- name: copy /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root

- name: restart nfs server
  service:
    name: nfs-kernel-server
    state: restarted
