apiVersion: v2
name: knit-db-postgres
description: knitfab database (postgres)
type: application
keywords:
  - knitfab
  - MLOps
  - Lineage Tracking
  - Workflow
  - Tag Based Workflow

version: v1.3.1
appVersion: v1.3.1-98d1e14
