
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.server }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Values.secret.server }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: knitfab
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cert }}
  tls.key: {{ .Values.key }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.ca }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Values.secret.ca }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: knitfab
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cacert }}
  tls.key: {{ .Values.cakey }}
