apiVersion: v2
name: knit-db-postgres
description: knitfab database (postgres)
type: application
keywords:
  - knitfab
  - MLOps
  - Lineage Tracking
  - Workflow
  - Tag Based Workflow

version: v1.2.1-beta
appVersion: v1.2.1-beta-72a9c5b
